version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
  - package-ecosystem: "pip"
    directory: "/backend/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/frontend/"
    schedule:
      interval: "weekly"
